version: "3.8"

services:
  ci_cd:
    container_name: ci_cd
    image: node:ci_cd
    build:
      context: .
      args:
        NODE_ENV: 'prod'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped